"""Baby sign language data for GL Signs tab."""

BABY_SIGNS = {
    "MORE": {
        "emoji": "🤌🤌",
        "how": "Touch all fingertips together on both hands. Tap them together twice.",
        "visual": "Both hands make a pinch shape. Tap fingertips together. Like squeezing a tiny ball.",
        "when": "Before offering more food, more play, more of anything",
        "category": "Essential",
        "priority": 1,
    },
    "ALL DONE": {
        "emoji": "🖐️🖐️",
        "how": "Open both hands, palms facing out. Twist wrists back and forth.",
        "visual": "Jazz hands! Palms out, shake them side to side like waving with both hands.",
        "when": "When finished eating, playing, bathing. Say 'all done!' while signing.",
        "category": "Essential",
        "priority": 2,
    },
    "MILK": {
        "emoji": "✊",
        "how": "Make a fist. Open and close it repeatedly. Like milking a cow.",
        "visual": "One hand: squeeze open, squeeze closed, squeeze open. Gentle pumping motion.",
        "when": "Before and during bottle/breastfeeding. 'Want milk?'",
        "category": "Essential",
        "priority": 3,
    },
    "EAT": {
        "emoji": "🤏👄",
        "how": "Pinch fingers together (like holding food). Tap to your mouth repeatedly.",
        "visual": "Flat O hand shape, bring to lips, tap tap tap. Like feeding yourself.",
        "when": "Before meals, when offering food. 'Time to eat!'",
        "category": "Mealtime",
        "priority": 4,
    },
    "WATER": {
        "emoji": "🤟👄",
        "how": "Make a W with three fingers. Tap your chin/lower lip.",
        "visual": "Index + middle + ring finger up (W shape). Tap your chin twice.",
        "when": "When offering water or any drink. 'Want water?'",
        "category": "Mealtime",
        "priority": 5,
    },
    "HELP": {
        "emoji": "👍✋",
        "how": "Make a thumbs up with one hand. Place it on your other open palm. Lift both up.",
        "visual": "Thumbs up sits on open palm. Both hands rise together. Like boosting someone up.",
        "when": "When GL is struggling. 'Need help? Sign help!'",
        "category": "Essential",
        "priority": 6,
    },
    "UP": {
        "emoji": "☝️",
        "how": "Point index finger up.",
        "visual": "One finger pointing to the sky. Simple!",
        "when": "When GL reaches up to be held. 'Want up?'",
        "category": "Essential",
        "priority": 7,
    },
    "DOWN": {
        "emoji": "👇",
        "how": "Point index finger down.",
        "visual": "One finger pointing to the ground.",
        "when": "When putting GL down. 'Going down!'",
        "category": "Essential",
        "priority": 8,
    },
    "PLAY": {
        "emoji": "🤙🤙",
        "how": "Extend thumb and pinky on both hands (hang loose). Twist wrists back and forth.",
        "visual": "Both hands: thumb + pinky out (shaka/hang loose). Wiggle/twist them.",
        "when": "When starting play time. 'Want to play?'",
        "category": "Playtime",
        "priority": 9,
    },
    "BOOK": {
        "emoji": "📖",
        "how": "Put palms together (like a closed book). Then open them flat (like opening a book).",
        "visual": "Hands together → open flat. Opening a book!",
        "when": "Before reading time. 'Want to read a book?'",
        "category": "Playtime",
        "priority": 10,
    },
    "SLEEP": {
        "emoji": "😴",
        "how": "Open hand in front of face. Slowly close fingers while drawing hand down. Eyes close.",
        "visual": "Fingers spread near face → slowly close into a fist while moving down. Mime falling asleep.",
        "when": "Before nap/bedtime. 'Time to sleep!'",
        "category": "Bedtime",
        "priority": 11,
    },
    "HURT": {
        "emoji": "👆👆",
        "how": "Point both index fingers at each other. Twist them back and forth.",
        "visual": "Both index fingers pointing at each other, close together. Twist/rotate them. Like pain radiating.",
        "when": "When GL seems uncomfortable. 'Does something hurt?'",
        "category": "Essential",
        "priority": 12,
    },
    "I LOVE YOU": {
        "emoji": "🤟",
        "how": "Extend thumb, index finger, and pinky. Keep middle and ring down.",
        "visual": "The rock-on sign but with thumb out too! Thumb + pointer + pinky = I Love You in ASL.",
        "when": "Anytime! Before bed, after hugs, just because.",
        "category": "Bedtime",
        "priority": 13,
    },
    "DADDY": {
        "emoji": "👋🤚",
        "how": "Open hand, fingers spread. Tap thumb to forehead.",
        "visual": "Five fingers spread wide. Thumb touches your forehead. Tap twice.",
        "when": "When Peter walks in. 'There's Daddy!'",
        "category": "Essential",
        "priority": 14,
    },
    "MOMMY": {
        "emoji": "👋🤚",
        "how": "Open hand, fingers spread. Tap thumb to chin.",
        "visual": "Five fingers spread wide. Thumb touches your chin. Tap twice.",
        "when": "When Gladys walks in. 'There's Mommy!'",
        "category": "Essential",
        "priority": 15,
    },
    "DOG": {
        "emoji": "🐕",
        "how": "Pat your thigh twice. Like calling a dog.",
        "visual": "Slap your thigh twice. 'Here boy!'",
        "when": "When you see a dog. 'Look, a dog!'",
        "category": "Playtime",
        "priority": 16,
    },
    "BATH": {
        "emoji": "🛁",
        "how": "Make fists and rub them up and down on your chest. Like scrubbing.",
        "visual": "Both fists on chest, rub up and down. Washing yourself!",
        "when": "Before bath time. 'Bath time!'",
        "category": "Bedtime",
        "priority": 17,
    },
    "DIAPER": {
        "emoji": "👶",
        "how": "Put hands at waist level. Tap the sides of your hips with open hands.",
        "visual": "Open hands tap your hips/waist area. Like patting where a diaper sits.",
        "when": "During diaper changes. 'Time for a new diaper!'",
        "category": "Essential",
        "priority": 18,
    },
}

CATEGORIES = {
    "All Signs": None,
    "Essential": "Essential",
    "Mealtime": "Mealtime",
    "Playtime": "Playtime",
    "Bedtime": "Bedtime",
}
